### ISSUE TITLE
nan outputs when the number of sampling steps is set to 1

### ISSUE THREAD

**Issue by Kinyugo** [archinetai/audio-diffusion-pytorch#15]
Setting the `num_steps` in `DiffusionSampler` to 1 leads to nan values when using a UNet. I tried replacing the UNet with an identity function and I do not get the same nans.

**Comment by flavioschneider** [comment]
I can't replicate this on my experiments. What `sigma_schedule` and `sampler` are you using?

**Comment by Kinyugo** [comment]
I am using the `KarrasSchedule` and `ADPM2Sampler`. I set the number of sampling steps to 1 just for testing purposes to ensure everything works correctly. 

As an aside, I was wondering how you selected the default parameters for the schedules, samplers and distribution. Is there a principled approach that one can follow to determine the best parameters or even some pointers?

**Comment by flavioschneider** [comment]
There isn't a predefined way to do that, but the sampling parameters are independent of training, so you can do experiments afterwards to see which configuration gives the best result. For the noise schedule, I did a few experiments with different models and picked the one that worked the best. You can find more details in Karras' paper (see citations of the readme)
