### ISSUE TITLE
text conditioned infinite ASMR generator?

### ISSUE THREAD

**Issue by lucidrains** [archinetai/audio-diffusion-pytorch#2]
you could be rich! just incepting the idea 😆

**Comment by flavioschneider** [comment]
Well... today I learned something 😂 should I use [this](https://zenodo.org/record/3889168#.Yv1QYexBy3I) to test the unconditioned model on dual channel audio?

**Comment by lucidrains** [comment]
@flavioschneider oh perfect! didn't even know they had a dataset haha

**Comment by nateraw** [comment]
omg yes

**Comment by yoyololicon** [comment]
please do this
