### ISSUE TITLE
Using the audio_975 model with colab fails

### ISSUE THREAD

**Issue by timohear** [archinetai/audio-diffusion-pytorch#21]
Hello,

I'm trying to get the colab to run with the new larger model available here:
https://huggingface.co/archinetai/audio-diffusion-pytorch/resolve/main/audio_975.pt

I've modified the colab to use the latest git code:
`!pip install -e git+https://github.com/archinetai/audio-diffusion-pytorch@main#egg=audio-diffusion-pytorch`

However loading the latest model fails with
`Can't get attribute 'CrossEmbed1d' on <module 'audio_diffusion_pytorch.modules' from '/usr/local/lib/python3.7/dist-packages/audio_diffusion_pytorch/modules.py'>`

Is there a way to get the new model to run?

**Comment by flavioschneider** [comment]
That model is an upsampler (`AudioDiffusionUpsampler`), hence it works differently than the model in the colab (also it's an older version, 0.0.31). In a week or so I might publish a larger, much better unconditional model in a new notebook.

**Comment by timohear** [comment]
Looking forward to it. Thank you
