### ISSUE TITLE
Add trainer

### ISSUE THREAD

**Issue by nateraw** [archinetai/audio-diffusion-pytorch#3]
Hey there, I have been following this project pretty closely...looks great. Could you share the lightning trainer you're using here/any associated scripts for training?

I've put together my own trainer with `accelerate` which is working fine, but would be nice to work out of the same one as you here for reproducibility sake.

**Comment by flavioschneider** [comment]
Thanks! It's something I have in my to-do list. I was thinking about adding a separate repository with the trainer to avoid polluting this one – the one I'm currently using has a lot of extra code that I need to refactor out.

**Comment by nateraw** [comment]
That's sorta what I figured! A separate repo or even just a separate folder here that's not included in the python package would be great. Happy to help wherever needed.

**Comment by flavioschneider** [comment]
Let me know if this works for you [`audio-diffusion-pytorch-trainer`](https://github.com/archinetai/audio-diffusion-pytorch-trainer)!

**Comment by nateraw** [comment]
Will have a look and follow up there! Thanks 😄
