### ISSUE TITLE
training with conditioning t5

### ISSUE THREAD

**Issue by nikuson** [archinetai/audio-diffusion-pytorch#34]
I didn’t quite understand how to start training with conditioning and how to arrange a dataset for this.

**Comment by jbmaxwell** [comment]
ditto... some sample code for conditional training would be awesome.

**Comment by flavioschneider** [comment]
Which part is not clear from the example in the readme?

```py
from audio_diffusion_pytorch import T5Embedder

# Declare the text embedding model 
embedder = T5Embedder(model='t5-base', max_length=64)

# Declare the diffusion model 
model = AudioDiffusionConditional(
    in_channels=1,
    # other params here...
    embedding_max_length=64,
    embedding_features=768,
)

# Encode text into embedding
embedding = embedder(["First batch item text...", "Second batch item text..."]) # [2, 64, 768]
x = torch.randn(2, 1, 2 ** 18) # Your waveform 

# Feed waveform and text into the model 
loss = model(x, embedding=embedding)

# Repeat this step multiple times in the training loop 
loss.backward()
```

**Comment by jbmaxwell** [comment]
Sorry... yes, clear enough.

**Comment by nikuson** [comment]
> Какая часть непонятна из примера в ридми?
> 
> ```python
> from audio_diffusion_pytorch import T5Embedder
> 
> # Declare the text embedding model 
> embedder = T5Embedder(model='t5-base', max_length=64)
> 
> # Declare the diffusion model 
> model = AudioDiffusionConditional(
>     in_channels=1,
>     # other params here...
>     embedding_max_length=64,
>     embedding_features=768,
> )
> 
> # Encode text into embedding
> embedding = embedder(["First batch item text...", "Second batch item text..."]) # [2, 64, 768]
> 
> # Your waveform (dummy example)
> x = torch.randn(2, 1, 2 ** 18) 
> 
> # Feed waveform and text embedding into the model 
> loss = model(x, embedding=embedding)
> 
> # Repeat this step multiple times in the training loop 
> loss.backward()
> ```

So where do you put the dataset?

**Comment by jbmaxwell** [comment]
I hadn't realized before, but there are two extra repos to help!

https://github.com/archinetai/audio-data-pytorch
https://github.com/archinetai/audio-diffusion-pytorch-trainer
