### ISSUE TITLE
example for Unconditional Generator fails

### ISSUE THREAD

**Issue by MultiTrickFox** [archinetai/audio-diffusion-pytorch#43]
I'm running the provided example for Unconditional Generator, but getting the following error:

<img width="1036" alt="Screen Shot 2023-01-19 at 12 10 59 PM" src="https://user-images.githubusercontent.com/39859227/213440085-4efc2cce-95ab-4c04-976b-f5aeed19449c.png">

* and switching to gpu runtime gives this error,

<img width="1165" alt="Screen Shot 2023-01-19 at 12 15 35 PM" src="https://user-images.githubusercontent.com/39859227/213440848-af8ff165-94fc-428e-9b3b-abb6e42677b3.png">

**Comment by flavioschneider** [comment]
There seems to be a bug in the flash attention implementation merged in `a-unet` please revert to version 0.0.12 with `pip install a-unet==0.0.12` for now.

**Comment by MultiTrickFox** [comment]
Thank you.
