### ISSUE TITLE
How to convert to wav file to listen to result?

### ISSUE THREAD

**Issue by dillfrescott** [archinetai/audio-diffusion-pytorch#46]
I am a bit confused how to do this. Any help would be appreciated! :)

**Comment by tralala87** [comment]
I would also like to know this. I can't seem to download the audio file after running the code.

**Comment by dillfrescott** [comment]
I don't think the audio file is actually being written anywhere. Just the data stored in memory I believe.

**Comment by tralala87** [comment]
What is the point then to advertise it as "text-to-music" generator? :(

**Comment by mangoleaf** [comment]
I have played around trying to save the tensors as wav files (sample below for others interested), however I seem to only receive audio files out that are complete static.

I would really appreciate it if someone can offer a correct solution to this. I would be happy to submit code adding a utility for this as well.

```
# Turn noise into new audio sample with diffusion
noise = torch.randn(1, 2, 2**18)
sample = model.sample(
    noise,
    text=['Bird chirping'],
    embedding_scale=5.0, # Higher for more text importance, suggested range: 1-15 (Classifier-Free Guidance Scale)
    num_steps=15 # Higher for better quality, suggested num_steps: 10-100
)


import soundfile as sf
def save_wav(tensor, path):
    tensor = tensor.squeeze()
    tensor = tensor / tensor.max()
    nparray = tensor.squeeze().numpy(force=True).astype('float32').T
    sf.write(path, nparray, samplerate=44100, format='wav')
    print("Done saving file")

save_wav(sample, "test_generated_sound.wav")
```

**Comment by flavioschneider** [comment]
This is a library for researchers to train audio diffusion models, no pre-trained models are provided here

**Comment by flavioschneider** [comment]
The correct way to save a tensor to `.wav` file is as follows:
```py
import torchaudio
sample_rate = 48000
torchaudio.save('test_generated_sound.wav', sample, sample_rate)
```
No additional utility or library is required for that
