### ISSUE TITLE
How to use our own background noisy dataset to generate sample?

### ISSUE THREAD

**Issue by haloha123** [archinetai/audio-diffusion-pytorch#48]
Thank you for sharing this awesome works!

How can I load our own dataset (for example: dataset with noisy background noise) into the prertrained diffusion model? It is possible to use pytorch dataloader?

Then use sampler. Finally get the sample output.

Thank you!!!

**Comment by flavioschneider** [comment]
This repository doesn't provide any pretrained models. Yes, you can use a pytorch dataloader. Here you will only find the model code that can be customized depending on the goal, you'll have to write your own training loop
